---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  POSTGRES_DB: authdb
  POSTGRES_USER: authuser
  POSTGRES_PASSWORD: authpass
  JWT_SECRET: devops-super-secret-key-2024
